---
title: "Word Frequency"
author: "Logan Calder"
date: "12/12/2017"
output: pdf_document
---


```{r packages}
library(lubridate)
library(tidytext)
library(tidyverse)
```

```{r load_data}
load("data_processed/strike_reports.RData")
```

```{r}
dim(strike_reports)
n_reports = 1062
top_n_words = 15
```

```{r}
words_ranked <- (strike_reports[1:n_reports,] %>%
    unnest_tokens(output = "word", input = "report_text") %>%
    anti_join(stop_words) %>%
    group_by(
        word
    ) %>% 
    summarize(
        frequency = length(word)
    ) %>%
    arrange(desc(frequency)) %>%
    mutate(
        word = factor(word, levels = word[1:top_n_words])
    ))[1:top_n_words,]
```

```{r}
words_ <-
    strike_reports[1:n_reports,] %>%
    unnest_tokens(output = "word", input = "report_text") %>%
    anti_join(stop_words) %>%
    transmute(
        year = year(report_created_date),
        quarter = quarter(report_created_date),
        word = factor(word, words_ranked$word)
    ) %>%
    filter(!is.na(word)) %>%
    group_by(
        year, quarter, word
    ) %>%
    summarize(
        frequency = length(word)
    ) 

```

```{r}
ggplot(words_ranked, mapping = aes(x = word, y = frequency)) + geom_col() +
    theme(axis.text.x = element_text(angle = -90))

ggplot(words_, mapping = aes(x = word, y = frequency)) + geom_col() + facet_grid(year~quarter) +
    theme(axis.text.x = element_text(angle = -90))
```

